using Sts2ContextCoach.Scoring;
using Sts2ContextCoach.State;

namespace Sts2ContextCoach.Llm;

/// <summary>One purchasable / pickable card in a shared row (reward or shop), with heuristic coach scores.</summary>
public sealed class LlmCoachCandidate
{
    public required string InternalName { get; init; }
    public bool Upgraded { get; init; }
    public int? EnergyCost { get; init; }
    public int? ShopPrice { get; init; }
    public bool ShopDiscounted { get; init; }
    public float AugmentBonus { get; init; }
    public string? AugmentReasonKey { get; init; }
    public required ScoreResult Heuristic { get; init; }

    /// <summary>Row identity for logging / cache; includes probe fields (can flicker per node).</summary>
    public string StableKey =>
        $"{InternalName}|u{(Upgraded ? 1 : 0)}|p{ShopPrice?.ToString() ?? "_"}|d{(ShopDiscounted ? 1 : 0)}";

    /// <summary>
    /// Batch dedupe key only. Must not include <see cref="ShopPrice"/> — probe results differ by DOM walk
    /// and would cause a different key per overlay card, superseding the HTTP request every frame.
    /// </summary>
    public string BatchStableKey =>
        $"{InternalName}|u{(Upgraded ? 1 : 0)}";

    public string AdviceMapKey => $"{InternalName}|u{(Upgraded ? 1 : 0)}";

    public static LlmCoachCandidate FromRuntime(
        string internalName,
        bool upgraded,
        int? cost,
        ShopEconomyContext? shopEco,
        float augmentBonus,
        string? augmentReasonKey,
        ScoreResult heuristic) =>
        new()
        {
            InternalName = internalName,
            Upgraded = upgraded,
            EnergyCost = cost,
            ShopPrice = shopEco?.CardPrice,
            ShopDiscounted = shopEco?.IsDiscounted ?? false,
            AugmentBonus = augmentBonus,
            AugmentReasonKey = augmentReasonKey,
            Heuristic = heuristic
        };
}

public enum LlmOverlayBatchStatus
{
    /// <summary>Heuristic mode or no batch for this overlay.</summary>
    Idle,

    /// <summary>Waiting for debounce or HTTP.</summary>
    Pending,

    /// <summary>Advice available for this batch key.</summary>
    Ready,

    /// <summary>HTTP/parse failure; overlay should fall back to heuristics.</summary>
    Failed
}

public sealed class LlmCardAdvice
{
    public required string CoachNote { get; init; }
    public int? CoachScore { get; init; }
}

/// <summary>Cached deck-level context generated by periodic LLM summary calls.</summary>
public sealed class LlmDeckProfile
{
    public required string Signature { get; init; }
    public DateTimeOffset GeneratedUtc { get; init; }
    public int? GeneratedFloor { get; init; }
    public int Version { get; init; } = 1;

    public string CorePlan { get; init; } = "";
    public List<string> Enablers { get; init; } = [];
    public List<string> Payoffs { get; init; } = [];
    public List<string> Risks { get; init; } = [];
    public List<string> Interactions { get; init; } = [];

    public List<string> ToSummaryLines(int maxLines)
    {
        var lines = new List<string>();
        if (!string.IsNullOrWhiteSpace(CorePlan))
            lines.Add($"plan: {CorePlan.Trim()}");

        AddBucket(lines, "enablers", Enablers, 3);
        AddBucket(lines, "payoffs", Payoffs, 3);
        AddBucket(lines, "risks", Risks, 2);
        AddBucket(lines, "interactions", Interactions, 4);

        if (maxLines <= 0)
            return [];
        return lines.Take(maxLines).ToList();
    }

    private static void AddBucket(List<string> lines, string name, List<string> source, int limit)
    {
        if (source.Count == 0) return;
        var text = string.Join("; ", source.Where(s => !string.IsNullOrWhiteSpace(s)).Take(limit).Select(s => s.Trim()));
        if (string.IsNullOrWhiteSpace(text)) return;
        lines.Add($"{name}: {text}");
    }
}

internal readonly struct LlmDeckProfileRefreshDecision
{
    public required bool ShouldSchedule { get; init; }
    public required string Signature { get; init; }
    public required string Reason { get; init; }
}
